### PR TITLE
adding a public accessor to JsonPatch to retrieve the contained opera…

### PR DESCRIPTION
**Pull request by tbrantb**
I have a case where I have a library that receives a JsonPatch doc. Before applying the patch to another Json doc, my library needs to validate the contents of the JsonPatch. For example you may not replace certain values at certain paths or you must have a particular role to be able to perform particular patch operations. So I need to iterate and validate each operation within the JsonPatch object in order to perform custom validation. In order to do this, I need JsonPatch class to be able to expose the underlying List<JsonPatchOperation>. This pull request has a change to include a public getOperations() method on the JsonPatch class to return an Immutable copy of the internal operations list.

### CODE REVIEW

**Comment by jasonchaffee** [comment]
+1 on needing this as well.

**Comment by jjlauer** [comment]
+1 Is this fork dead as well the original project?  A very simple PR that I need as well.

**Comment by jasonchaffee** [comment]
@jjlauer It is looking like they are not merging and/or replying to any PR that hasn't been submitted by someone from Box or isn't for Box.  I am going to create my own fork and start maintaining there as open source that isn't tied to any organization.  See https://github.com/dogote/json-patch

**Comment by tbrantb** [comment]
Clearly this is not going to be adopted by this project. Closing to get it out of the list of things I care about.

**Pull request closed without merging**
